apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-photowall
  labels:
    app: photowall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photowall
  template:
    metadata:
      labels:
        app: photowall
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: photowall
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: photowall-files
              subPath: photowall-files
      volumes:
      - name: photowall-files
        hostPath:
          path: /srv/data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: photowall
  name: photowall-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 3000
  selector:
    app: photowall
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: photowall-ingress
spec:
  rules:
  - host: photowall.hacks.webfejleszto.info
    http:
      paths:
      - path: /
        backend:
          serviceName: photowall-service
          servicePort: 3000
